# Development profile
quarkus:
  http:
    port: 8081
  dev-ui:
    always-include: true
  log:
    level: INFO
    category:
      "org.techsolution": DEBUG
      "io.quarkus": INFO
  mongodb:
    connection-string: ${MONGODB_URI_DEV:mongodb://localhost:27017}
    database: ${MONGODB_DB_DEV:aiwebhook}

app:
  name: AI Webhook
  version: 1.0.0
  env: dev

openai:
  api-key: ${OPENAI_API_KEY:-}
  base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1/responses}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:7957539358:AAHec5jxQVahJIAKuEnPv6AdcxZ-lKepbSQ}
    base-url: ${TELEGRAM_BOT_BASE_URL:https://api.telegram.org}
    default-chat-id: ${TELEGRAM_DEFAULT_CHAT_ID:6432338413}
  webhook:
    api-key: asd123qwe
