# Production profile
quarkus:
  log:
    level: INFO
    category:
      "org.techsolution": INFO
  mongodb:
    connection-string: ${MONGODB_URI}
    database: ${MONGODB_DB:aiwebhook}

app:
  env: prod
