# AI Webhook - Application Config
# Base config (shared all profiles)

quarkus:
  smallrye-openapi:
    path: /q/openapi
    ui:
      path: /q/swagger-ui
app:
  name: AI Webhook
  version: 1.0.0
  env: sit
