# Development profile
quarkus:
  http:
    port: 8080
  dev-ui:
    always-include: true
  log:
    level: INFO
    file:
      enable: true
      path: logs/app-dev.log
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) %s%e%n"
    category:
      "com.avrist": DEBUG
      "io.quarkus": INFO
  mongodb:
    connection-string: ${MONGODB_URI}
    database: ${MONGODB_DB}

app:
  name: AI Webhook
  version: 1.0.0
  env: sit

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1/responses}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    base-url: ${TELEGRAM_BOT_BASE_URL:https://api.telegram.org}
  webhook:
    api-key: ${TELEGRAM_BOT_API_KEY}
